framework:
    messenger:
        failure_transport: failed

        transports:
            async_priority_high:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        default_publish_routing_key: async-priority-high
                        name: async_priority_high
                    queues:
                        messages_high:
                            binding_keys: [async-priority-high]
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            async_priority_medium:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        default_publish_routing_key: async-priority-medium
                        name: async_priority_medium
                    queues:
                        messages_medium:
                            binding_keys: [async-priority-medium]
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            async_priority_low:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        default_publish_routing_key: async-priority-low
                        name: async_priority_low
                    queues:
                        messages_low:
                            binding_keys: [async-priority-low]
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

            failed:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        default_publish_routing_key: failed
                        name: failed
                    queues:
                        messages_low:
                            binding_keys: [failed]
                retry_strategy:
                    max_retries: 10
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

        routing:
            App\Message\CreateGasStationMessage: async_priority_high
            App\Message\UpdateGasStationMessage: async_priority_high
            App\Message\CreateGasPriceMessage: async_priority_low
            App\Message\GeocodingAddressMessage: async_priority_medium
            App\Message\ErrorGeocodingAddressMessage: async_priority_medium
            App\Message\CreateGooglePlaceTextsearchMessage: async_priority_medium
            App\Message\CreateGooglePlaceAnomalyMessage: async_priority_high
            App\Message\CreateGooglePlaceDetailsMessage: async_priority_high
